export const SLOT_INIT = 'SLOT_INIT';
export const SLOT_LOADING = 'SLOT_LOADING';
export const SLOT_LOAD_COMPLETE = 'SLOT_LOAD_COMPLETE';

export const CONTROLS_TOGGLE_SELECT_LINES = 'CONTROLS_TOGGLE_SELECT_LINES';
export const CONTROLS_SHOW_SELECT_LINES = 'CONTROLS_SHOW_SELECT_LINES';
export const CONTROLS_HIDE_SELECT_LINES = 'CONTROLS_HIDE_SELECT_LINES';
export const CONTROLS_SELECT_LINE = 'CONTROLS_SELECT_LINE';

export const CONTROLS_TOGGLE_SELECT_COINS = 'CONTROLS_TOGGLE_SELECT_COINS';
export const CONTROLS_SHOW_SELECT_COINS = 'CONTROLS_SHOW_SELECT_COINS';
export const CONTROLS_HIDE_SELECT_COINS = 'CONTROLS_HIDE_SELECT_COINS';
export const CONTROLS_SELECT_COIN = 'CONTROLS_SELECT_COIN';

// @todo remove this cheat
export const CONTROLS_CHEAT_START_BONUSGAME = 'CONTROLS_CHEAT_START_BONUSGAME';
export const CONTROLS_CHEAT_START_FREESPINS = 'CONTROLS_CHEAT_START_FREESPINS';

export const CONTROLS_COINS_CHANGE = 'CONTROLS_COINS_CHANGE';
export const CONTROLS_CHANGE_ACTIVE_LINES = 'CONTROLS_CHANGE_ACTIVE_LINES';
export const CONTROLS_MAX_LINES = 'CONTROLS_MAX_LINES';
export const CONTROLS_PAYLOAD = 'CONTROLS_PAYLOAD';
export const CONTROLS_RESUME_GAME = 'CONTROLS_RESUME_GAME';
export const CONTROLS_SPIN_START = 'CONTROLS_SPIN_START';
export const CONTROLS_SPIN_STOP = 'CONTROLS_SPIN_STOP';

export const FREESPINS_START = 'FREESPINS_START';
export const FREE_SPINS_SET_COUNT = 'FREE_SPINS_SET_COUNT';
export const FREE_SPINS_HIDE_START_NOTIFICATION = 'FREE_SPINS_HIDE_START_NOTIFICATION';
export const FREE_SPINS_HIDE_END_NOTIFICATION = 'FREE_SPINS_HIDE_END_NOTIFICATION';
export const FREESPINS_END = 'FREESPINS_END';
export const FREESPINS_CHANGE_COUNT = 'FREESPINS_CHANGE_COUNT';

export const SLOT_SET_ID_SYMBOLS_MAP = 'SLOT_SET_ID_SYMBOLS_MAP';
export const SLOT_SET_PAY_SCHEDULE = 'SLOT_SET_PAY_SCHEDULE';

export const SLOT_REEL_START_ROTATE = 'SLOT_REEL_START_ROTATE';
export const SLOT_REEL_STOP_ROTATE = 'SLOT_REEL_STOP_ROTATE';
export const SLOT_REELS_STOPPED = 'SLOT_REELS_STOPPED';

export const SLOT_START_SHOWING_LINES = 'SLOT_START_SHOWING_LINES';
export const SLOT_SHOWING_LINES = 'SLOT_SHOWING_LINES';
export const SLOT_SHOWING_LINES_LOOP = 'SLOT_SHOWING_LINES_LOOP';
export const SLOT_LINES_SHOWED = 'SLOT_LINES_SHOWED';
export const SLOT_CONTINUE_AFTER_SPIN = 'SLOT_CONTINUE_AFTER_SPIN';

export const FREEGAME_GAME_SHOW = 'FREEGAME_GAME_SHOW';
export const FREEGAME_GAME_HIDE = 'FREEGAME_GAME_HIDE';
export const FREEGAME_CLICK_ON_PIN = 'FREEGAME_CLICK_ON_PIN';
export const FREEGAME_START_HIT = 'FREEGAME_START_HIT';
export const FREEGAME_SET_RESULT_HIT_ON_PIN = 'FREEGAME_SET_RESULT_HIT_ON_PIN';
export const FREEGAME_HIT_ON_COMPLETE = 'FREEGAME_HIT_ON_COMPLETE';
export const FREEGAME_UNLOCK_ITEMS_FOR_CLICK = 'FREEGAME_UNLOCK_ITEMS_FOR_CLICK';


export const SLOT_START_SPECIAL_SYMBOLS_ANIMATION = 'SLOT_START_SPECIAL_SYMBOLS_ANIMATION';
export const SLOT_SHOW_INFO_WINDOW = 'SLOT_SHOW_INFO_WINDOW';
export const SLOT_HIDE_INFO_WINDOW = 'SLOT_HIDE_INFO_WINDOW';

export const SLOT_PLAY_SOUND = 'SLOT_PLAY_SOUND';
