export const LOBBY_INIT = 'LOBBY_INIT';
export const LOBBY_PARSE_LEVELS = 'LOBBY_PARSE_LEVELS';
export const LOBBY_SET_GAMES_INFO_LIST = 'LOBBY_SET_GAMES_INFO_LIST';
export const LOBBY_SET_USER_INFO = 'LOBBY_SET_USER_INFO';
export const LOBBY_SET_USER_LEVEL_UP = 'LOBBY_SET_USER_LEVEL_UP';

export const LOBBY_SOUNDS_TOOGLE = 'LOBBY_SOUNDS_TOOGLE';

